### PR TITLE
Fix 500 Errors - performance tuning

### PR DESCRIPTION
**Pull request by volbrene**
We had problems with 500 errors if kong get high traffic with siege. This issue could be fixed with my changes.

### CODE REVIEW

**Comment by alexashley** [comment]
@volbrene I'm happy to merge this, but it seems like this would indicate a problem upstream in Kong. 

Do you have an example stack trace?

**Comment by volbrene** [comment]
@alexashley  Yes, this is my stacktrace from kong:

`[error] 31#0: *1034060 lua coroutine: runtime error: /usr/local/custom/kong/plugins/path-prefix/handler.lua:9: attempt to index local 'conf' (a nil value)
stack traceback:
coroutine 0:
/usr/local/custom/kong/plugins/path-prefix/handler.lua: in function 'escape_hyphen'
/usr/local/custom/kong/plugins/path-prefix/handler.lua:60: in function </usr/local/custom/kong/plugins/path-prefix/handler.lua:42>
coroutine 1:
[C]: in function 'resume'
coroutine.wrap:21: in function <coroutine.wrap:21>
/usr/local/share/lua/5.1/kong/init.lua:694: in function 'access'
access_by_lua(nginx-kong.conf:90):2: in main chunk, client: 172.31.25.165, server: kong, request: "GET /api-adapter/v1/posts HTTP/1.1", host: "api.test-api.de"

2019/11/20 07:56:53 [error] 31#0: *1034060 [kong] init.lua:701 /usr/local/custom/kong/plugins/path-prefix/handler.lua:9: attempt to index local 'conf' (a nil value), client: 172.31.25.165, server: kong, request: "GET /api-adapter/v1/posts HTTP/1.1", host: "api.test-api.de"
172.31.25.165 - - [20/Nov/2019:07:56:53 +0000] "GET /api-adapter/v1/posts HTTP/1.1" 200 37675 "-" "Mozilla/5.0 (apple-x86_64-darwin17.7.0) Siege/4.0.4"
172.31.25.165 - - [20/Nov/2019:07:56:53 +0000] "GET /api-adapter/v1/posts HTTP/1.1" 500 42 "-" "Mozilla/5.0 (apple-x86_64-darwin17.7.0) Siege/4.0.4"
2019/11/20 07:56:53 [notice] 31#0: *1034060 [kong] handler.lua:68 [path-prefix] rewriting /api-adapter/v1/posts to /v1/posts, client: 172.31.25.165, server: kong, request: "GET /api-adapter/v1/posts HTTP/1.1", host: "api.test-api.de"

2019/11/20 07:56:53 [error] 31#0: *1034062 lua coroutine: runtime error: /usr/local/custom/kong/plugins/path-prefix/handler.lua:9: attempt to index local 'conf' (a nil value)
stack traceback:
coroutine 0:
/usr/local/custom/kong/plugins/path-prefix/handler.lua: in function 'escape_hyphen'
/usr/local/custom/kong/plugins/path-prefix/handler.lua:60: in function </usr/local/custom/kong/plugins/path-prefix/handler.lua:42>
coroutine 1:
[C]: in function 'resume'
coroutine.wrap:21: in function <coroutine.wrap:21>
/usr/local/share/lua/5.1/kong/init.lua:694: in function 'access'
access_by_lua(nginx-kong.conf:90):2: in main chunk, client: 172.31.25.165, server: kong, request: "GET /api-adapter/v1/posts`

**Comment by alexashley** [comment]
@volbrene Thanks for the info. Still seems to me like a Kong issue, but you're correct that the plugin only needs to fetch its config once. What version of Kong are you testing with? Would you mind sharing the Siege command you're running?

**Comment by alexashley** [comment]
@volbrene Thanks for the contribution!

**Comment by volbrene** [comment]
I am using Kong 1.4. The siege command was siege -u https://test.de/api-adapter/v1/posts for example. Simple standard Command.

**Pull request merged**
